// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfPowerTools.Models;

public partial class Factura
{
    public int Id { get; set; }

    public string NombreUsuario { get; set; }

    public string ApellidoUsuario { get; set; }

    public string NomCentroFormacion { get; set; }

    public string NombreProducto { get; set; }

    public string TipoProducto { get; set; }

    public int? Cantidad { get; set; }
}