// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfPowerTools.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string TipoDocumento { get; set; }

    public string Documento { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string SegundoApellido { get; set; }

    public int? Edad { get; set; }

    public string Sexo { get; set; }

    public DateTime? FechaNac { get; set; }

    public string Direccion { get; set; }

    public string CodigoPostal { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Nacionalidad { get; set; }

    public string Departamento { get; set; }

    public string Municipio { get; set; }

    public string EstadoCivil { get; set; }

    public string NombreCentrodeFormacion { get; set; }
}